### ISSUE TITLE
Mozilla's Global Sprint (June 1st and 2nd 2017) 

### ISSUE THREAD

**Issue by paulvill** [paulvill/paulvill.github.io#17]
This issue is unashamedly inspired by Bionode's [issue](https://github.com/bionode/bionode/issues/44)

"[Mozilla’s Global Sprint](https://mozilla.github.io/global-sprint/) is a fun, fast-paced and two-day collaborative event to hack and build projects for a healthy Internet. A diverse network of scientists, educators, artists, engineers and others come together in person and online to innovate in the open. [Get your tickets now!](https://mozilla.github.io/global-sprint/register/)"

Ways to contribute to The Embryo Digital Atlas during sprint:

Some HTML and CSS knowledge required

- [x] Adjust the overall layout of the website: [issue #10](https://github.com/paulvill/paulvill.github.io/issues/10) 
	- [new layout](https://paulvill.github.io/template)
- [x] Adjust the list of datasets - There is a potential list of model organisms that we would like to feature in the future: [issue #18](https://github.com/paulvill/paulvill.github.io/issues/18)
- [x] Explanation going with datasets: [issue #21](https://github.com/paulvill/paulvill.github.io/issues/21)
	- [Updatable list of datasets](https://paulvill.github.io/layout_test/json-populate-demo.html)
- [x] Explanation for keys: [issue #19](https://github.com/paulvill/paulvill.github.io/issues/19)
	- [Hit the question mark](https://paulvill.github.io/layout_test/index.html)
- [x] "About" page: [issue #22](https://github.com/paulvill/paulvill.github.io/issues/22)
- [x] Side bar with interactions: [issue #25](https://github.com/paulvill/paulvill.github.io/issues/25)
- [x] Adapt the layout to smaller screen, phones, tablets: [issue #9](https://github.com/paulvill/paulvill.github.io/issues/9)

Some Javascript knowledge required
- [x] Incorporate an animation during loading time: [issue #12](https://github.com/paulvill/paulvill.github.io/issues/12)
	- [animation](https://paulvill.github.io/layout_test/loadingdemo.html)
- [x] Adapt the visualization interface to 3D data - orthoslices: [issue#6](https://github.com/paulvill/paulvill.github.io/issues/6)
	- [volume rendering](https://paulvill.github.io/beta/volume_rendering) - move in 3d with 'A','S','D','W', move in time and z with the arrows, and change channel with space
- [x] Include tactile interaction: [issue #9](https://github.com/paulvill/paulvill.github.io/issues/9)

Challenging issue
- [ ] Build a data storage platform with [OMERO](https://www.openmicroscopy.org/site) and combine it with the visualization platform: [issue #4](https://github.com/paulvill/paulvill.github.io/issues/4)

**Comment by snowwitje** [comment]
brainstorming etherpad: https://public.etherpad-mozilla.org/p/globalsprint2017-embryodigitalatlas

**Comment by paulvill** [comment]
Hi everyone @snowwitje @defenestrated @chitech @0xStarcat

I just updated the curated list of issues that we had for the Mozilla Global Sprint with the progress we made during the two days. This is really great!!

To wrap everything up, we just need to combine all the parts. We will meet on Tuesday with Sam (@defenestrated) to work on that and update the main website. 

Jeff (@0xStarcat) raised an issue of compatibility between his code and the `Materialize` library that Christine (@chitech) used. Christine, do you think you could have an answer for Jeff on this issue?

Alissa (@snowwitje), could you maybe add a support for text popping up when hitting the tabs 'about project', 'acknowledgments', 'contact'? I will then fill the content for it. We should use the [sample page](https://github.com/paulvill/paulvill.github.io/files/1044931/eda_sitemocks-sample-page.pdf) in the mockup.

Thanks a lot for your contributions!!

Paul

**Comment by chitech** [comment]
Thanks for the summary Paul @paulvill . I responded to Jeff and will work on solution that doesn't use Matrialize for legend styles and javascript.

**Comment by snowwitje** [comment]
Hey @paulvill. I'll take on your task in the next few days.

**Comment by paulvill** [comment]
Thanks @chitech and @snowwitje !
